apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-claim
          image: 192.168.1.11:5000/publisher
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "2000m"
          imagePullPolicy: 
          ports:
            - containerPort: 5000
      volumes:
      - name: postgres-pv-claim
        persistentVolumeClaim:
          claimName: postgres-pv-claim